### PR TITLE
Corrected offsets for SkyrimVR

### LINKED ISSUE #2: VR version crash
I compiled the VR version of this and it seems to crash the game when entering dialogue. I imagine this is the same crash that caused you to pull this VR version from Nexus.

Although I haven't really dug through your code, I am guessing the issue is most likely with one or more of the VR memory addresses under the hookedAddresses namespace in Hooks.cpp. I have done some assembly language programming many years ago, as well as Windows development in C++ also many years ago. I was trying to see if I could find the problem.

Can you tell me what program you use to determine those offsets? I figure it must be a disassembler of some kind, but I haven't used those before, so I don't know where to start.

### PR DESCRIPTION
**Pull request by drfuzzyness**
Resolves #2

### CODE REVIEW

**Comment by drfuzzyness** [comment]
Hold off on merging until I've tested this for more than a few hours

**Comment by drfuzzyness** [comment]
I don't think there are any issues of CTD, but it seems like there are still a few issues in the VR variant with:

- Fuz always forces subtitles, not just for specific lines
- Not every silent line gets a voice line injected

I'll look more into that next weekend if I can.

**Comment by shadeMe** [comment]
> 
> 
> I don't think there are any issues of CTD, but it seems like there are still a few issues in the VR variant with:
> 
>     * Fuz always forces subtitles, not just for specific lines
> 
>     * Not every silent line gets a voice line injected
> 
> 
> I'll look more into that next weekend if I can.

Okay, then I'll hold off on merging this PR until all issues have been fixed.

**Comment by Drakonas** [comment]
Any progress on this @drfuzzyness? It's been quite a few weekends since.

**Comment by drfuzzyness** [comment]
> quite a few weekends

> 5 months have passed

That it has. I wracked my brain with trying to figure out what the VR subtitle enable/disable function is doing but I can't make heads or tails of it.

The VR subtitle load function only shares half the code of SkyrimSE function, but includes a few extra instructions after the normal FuzRoDo for SE injection that when I fiddle with seem to just crash the game whenever subtitles show up. I'm certain someone with more reverse engineering experience could figure out what's going on but I couldn't figure it out.

As it stands, FuzRoDo for VR can properly inject the audio lines for all unvoiced lines but the subtitles will be forced on for every dialog line, ignoring the user preferences on their "Dialog Subtitles" settings page.

**Comment by Drakonas** [comment]
What would be displayed in the subtitles? null data? gibberish? Could it produce crashes? Having a partially usable plugin, to me, is better than nothing. There are certain esp's that crash when trying to export dialogues with CreationKit for use with Silent Voice Generator, so Fuz Ro Doh is the only option for those mods, and I am forced to not use them until Fuz Ro Doh has some form of update. I know you can notice I'm anxious on this matter, but I've patiently waited for 5 months since shadeMe took the half-broken version off the Nexus... Unfortunately, I can understand that releasing a mod that has an inkling of possibility to produce crashes brings in tons of angry people saying "Why it broke? HALP", so if releasing it as such is out of the question, I guess we'll just have to wait until someone comes along to look at this. :(

**Comment by drfuzzyness** [comment]
The latest version properly displays subtitles and properly injects the silent voices. It merely forces subtitles on for EVERY conversation that has subtitles.

I've used the [latest alpha 3 build](https://github.com/shadeMe/Fuz-Ro-D-oh-64/issues/2#issuecomment-633285465) on a save file that has gone on 60 hours with no crashes that I can attribute to Fuz Ro Doh for VR. 

I haven't seen any complaints of issues in other threads and I've seen this build tossed around on _other_ forums without any complaints. The only difference between this build and a final Nexus build would probably be installer packaging and using a real version number for tracking.

**Comment by shadeMe** [comment]
Closing this as VR support was removed from the codebase after the Anniversary Edition update.

**Pull request closed without merging**
